apiVersion: v1
kind: Service

metadata:
  name: stock-sync-postgres
  labels:
    app.kubernetes.io/name: stock-sync-postgres
    app.kubernetes.io/part-of: stock-sync

spec:
  selector:
    app.kubernetes.io/name: stock-sync-postgres

  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
