apiVersion: v1
kind: Secret

metadata:
  name: stock-sync-secrets

type: Opaque

stringData:
  POSTGRES_DB: stock_sync
  POSTGRES_USER: stock_sync
  POSTGRES_PASSWORD: stock_sync
  DATABASE_URL: postgres://stock_sync:stock_sync@stock-sync-postgres:5432/stock_sync
