apiVersion: v1
kind: ConfigMap

metadata:
  name: stock-sync-web-config
  labels:
    app.kubernetes.io/part-of: stock-sync

data:
  NODE_ENV: "production"
  PORT: "3000"
  REACT_APP_PUBLIC_API_URL: "http://stocksync.akira.home.arpa"
