apiVersion: v1
kind: Service

metadata:
  name: stock-sync-web
  labels:
    app.kubernetes.io/name: stock-sync-web
    app.kubernetes.io/part-of: stock-sync

spec:
  selector:
    app.kubernetes.io/name: stock-sync-web

  ports:
    - name: http
      port: 80
      targetPort: http
