name: CI Lint

on:
  workflow_call:

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup workspace
        uses: ./.github/actions/setup-pnpm

      - name: Lint
        run: pnpm lint
